// src/Frontend/angular/src/app/pages/auth/callback.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-callback',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="flex items-center justify-center min-h-screen">
      <div class="text-center" *ngIf="!error">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
        <p class="text-gray-600">Processando autenticação...</p>
      </div>
      <div class="text-center" *ngIf="error">
        <p class="text-red-600 mb-4">{{ error }}</p>
        <a href="/auth/login" class="text-blue-600 hover:underline">Tentar novamente</a>
      </div>
    </div>
  `,
})
export class CallbackComponent implements OnInit {
  error: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private authService: AuthService
  ) {}

  async ngOnInit(): Promise<void> {
    const code = this.route.snapshot.queryParamMap.get('code');
    const state = this.route.snapshot.queryParamMap.get('state');

    if (!code || !state) {
      this.error = 'Parâmetros de autenticação ausentes';
      return;
    }

    const success = await this.authService.handleCallback(code, state);
    if (success) {
      this.router.navigate(['/']);
    } else {
      this.error = 'Falha na autenticação. Tente novamente.';
    }
  }
}

// src/Frontend/nextjs/src/app/auth/callback/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { handleCallback } from '@/lib/auth';
import { Suspense } from 'react';

function CallbackContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const code = searchParams.get('code');
    const state = searchParams.get('state');

    if (!code || !state) {
      setError('Parâmetros de autenticação ausentes');
      return;
    }

    handleCallback(code, state)
      .then(success => {
        if (success) {
          router.replace('/');
        } else {
          setError('Falha na autenticação. Tente novamente.');
        }
      })
      .catch(err => {
        console.error('Auth callback error:', err);
        setError('Erro inesperado na autenticação.');
      });
  }, [searchParams, router]);

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center p-8">
          <div className="text-red-500 text-xl mb-4">⚠️</div>
          <p className="text-red-600 dark:text-red-400 mb-4">{error}</p>
          <a href="/auth/login" className="text-blue-600 hover:underline">Tentar novamente</a>
        </div>
      </div>
    );
  }

  return (
    <div className="flex items-center justify-center min-h-screen">
      <div className="text-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
        <p className="text-gray-600 dark:text-gray-400">Processando autenticação...</p>
      </div>
    </div>
  );
}

export default function CallbackPage() {
  return (
    <Suspense fallback={
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    }>
      <CallbackContent />
    </Suspense>
  );
}
