// src/Frontend/angular/src/app/pages/admin/categories.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { BaseResultList, CategoryResponse } from '../../core/models/api.interfaces';

@Component({
  selector: 'app-categories',
  standalone: true,
  imports: [CommonModule, RouterLink, FormsModule],
  template: `
    <div class="space-y-4">
      <div class="flex items-center justify-between">
        <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Categorias</h1>
        <a routerLink="/admin/categories/create" class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm">➕ Nova</a>
      </div>
      <div class="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800">
        <div class="p-4 border-b border-gray-200 dark:border-gray-800">
          <input type="text" placeholder="Buscar..." [(ngModel)]="search"
            class="w-full px-3 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white" />
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead><tr class="border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
              <th class="text-left p-4 font-medium text-gray-500">Nome</th>
              <th class="text-left p-4 font-medium text-gray-500">Descrição</th>
              <th class="text-left p-4 font-medium text-gray-500">Subcategorias</th>
              <th class="text-right p-4 font-medium text-gray-500">Ações</th>
            </tr></thead>
            <tbody>
              <tr *ngIf="loading"><td colspan="4" class="p-4 text-center text-gray-400">Carregando...</td></tr>
              <tr *ngFor="let c of filtered" class="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                <td class="p-4 font-medium text-gray-900 dark:text-white">{{ c.name }}</td>
                <td class="p-4 text-gray-600 dark:text-gray-400">{{ c.description || '-' }}</td>
                <td class="p-4 text-gray-600 dark:text-gray-400">{{ c.subCategories?.length || 0 }}</td>
                <td class="p-4 text-right flex justify-end gap-2">
                  <a [routerLink]="['/admin/categories', c.id, 'edit']" class="p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg">✏️</a>
                  <button (click)="del(c)" class="p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg">🗑️</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  `,
})
export class CategoriesComponent implements OnInit {
  items: CategoryResponse[] = [];
  loading = true;
  search = '';

  get filtered() { return this.items.filter(c => c.name.toLowerCase().includes(this.search.toLowerCase())); }

  constructor(private http: HttpClient) {}
  async ngOnInit(): Promise<void> { await this.load(); }

  async load(): Promise<void> {
    this.loading = true;
    const res = await this.http.get<BaseResultList<CategoryResponse>>(`${environment.apiUrl}/v1/categories`, { params: { PageSize: 100 } }).toPromise();
    if (res?.success) this.items = res.data;
    this.loading = false;
  }

  async del(c: CategoryResponse): Promise<void> {
    if (!confirm(`Excluir "${c.name}"?`)) return;
    await this.http.delete(`${environment.apiUrl}/v1/categories/${c.id}`).toPromise();
    await this.load();
  }
}

// src/Frontend/nextjs/src/app/(dashboard)/admin/categories/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { categoryService } from '@/services';
import { CategoryResponse } from '@/types/api';
import { Plus, Edit, Trash2, Search } from 'lucide-react';
import Link from 'next/link';

export default function CategoriesPage() {
  const [categories, setCategories] = useState<CategoryResponse[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [deleting, setDeleting] = useState<string | null>(null);

  const load = async () => {
    setLoading(true);
    try {
      const res = await categoryService.getAll();
      if (res.success) setCategories(res.data);
    } finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  const handleDelete = async (id: string, name: string) => {
    if (!confirm(`Tem certeza que deseja excluir "${name}"?`)) return;
    setDeleting(id);
    try {
      await categoryService.delete(id);
      await load();
    } finally { setDeleting(null); }
  };

  const filtered = categories.filter(c =>
    c.name.toLowerCase().includes(search.toLowerCase()) ||
    c.description?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Categorias</h1>
        <Link href="/admin/categories/create" className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
          <Plus size={16} /> Nova Categoria
        </Link>
      </div>

      <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800">
        <div className="p-4 border-b border-gray-200 dark:border-gray-800">
          <div className="relative">
            <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input type="text" placeholder="Buscar categorias..." value={search} onChange={e => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white" />
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
                <th className="text-left p-4 font-medium text-gray-500 dark:text-gray-400">Nome</th>
                <th className="text-left p-4 font-medium text-gray-500 dark:text-gray-400">Descrição</th>
                <th className="text-left p-4 font-medium text-gray-500 dark:text-gray-400">Subcategorias</th>
                <th className="text-right p-4 font-medium text-gray-500 dark:text-gray-400">Ações</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                Array.from({ length: 5 }).map((_, i) => (
                  <tr key={i} className="border-b border-gray-100 dark:border-gray-800">
                    <td colSpan={4} className="p-4"><div className="h-4 bg-gray-200 dark:bg-gray-700 rounded animate-pulse" /></td>
                  </tr>
                ))
              ) : filtered.length === 0 ? (
                <tr><td colSpan={4} className="p-8 text-center text-gray-500">Nenhuma categoria encontrada</td></tr>
              ) : filtered.map(cat => (
                <tr key={cat.id} className="border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-800/50">
                  <td className="p-4 font-medium text-gray-900 dark:text-white">{cat.name}</td>
                  <td className="p-4 text-gray-600 dark:text-gray-400">{cat.description || '-'}</td>
                  <td className="p-4 text-gray-600 dark:text-gray-400">{cat.subCategories?.length || 0}</td>
                  <td className="p-4 text-right">
                    <div className="flex justify-end gap-2">
                      <Link href={`/admin/categories/${cat.id}/edit`} className="p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded-lg">
                        <Edit size={16} />
                      </Link>
                      <button onClick={() => handleDelete(cat.id, cat.name)} disabled={deleting === cat.id}
                        className="p-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg disabled:opacity-50">
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
